import dbUserAnimal from "../firebase/Database/Functions/dbUserAnimal";

beforeAll(() => {

    // CATS DISEASES 
    /*
    //dbUserAnimal.addDiseaseDescription(disease,description,"Cat");
    dbUserAnimal.addDiseaseDescription("Acne","Feline acne is a problem seen in cats primarily involving the formation of blackheads accompanied by inflammation on the cat's chin and surrounding areas that can cause lesions, alopecia, and crusty sores.This problem can happen once, be reccurring, or even persistent throughout the cat's life.","Cat");
    dbUserAnimal.addDiseaseDescription("Aspergillosis","Aspergillosis is an infection, usually of the lungs, caused by the fungus Aspergillus. A ball of fungus fibers, blood clots, and white blood cells may form in the lungs or sinuses. Cats may have no symptoms or may cough up blood or have a fever, chest pain, and difficulty breathing.","Cat");
    dbUserAnimal.addDiseaseDescription("Cancer","Cancer in cats is the leading cause of death among cats. It is caused by uncontrolled cell growth, and affects a wide range of cell types and organs in the body. Feline cancer initially manifests as a lump or bump on any parts of the body. It rapidly grows in the affected cell; attaches itself to the tissue under the skin in that area; and, depending on the tumour, it can spread to other parts of the body.","Cat");
    dbUserAnimal.addDiseaseDescription("Coccidia","Coccidia is a protozoan that infects the intestinal tract of cats and other species and causes coccidiosis. It is a single-celled organism and while it isn't a worm or an egg, it is still a type of intestinal parasite. Signs of Coccidia in cats are : diarrhea,crying when defecating,sensitive when its belly is pressed,dehydration with sunken eyes and skin tenting,vomiting,loss of appetite and lethargy","Cat");
    dbUserAnimal.addDiseaseDescription("Coronavirus","Feline Coronavirus (FCoV) is a common viral infection in cats. It generally causes asymptomatic infection, but can cause mild diarrhea. As yet poorly understood changes in the virus can give rise to mutants that lead to the development of feline infectious peritonitis.Most cats infected with a FCoV eliminate virus following infection, but some cats may develop a persistent infection.FCoV is not the same virus as SARS-CoV-2 that causes the novel coronavirus (COVID-19)","Cat");
    dbUserAnimal.addDiseaseDescription("Cystitis","Cystitis in cats, also known as FIC (Feline Idiopathic Cystitis) affects a cat’s bladder and urinary tract and is usually triggered by stress.Treating Cystitis in cats usually involves a combination of changes both to the cat’s diet and to their home environment in order to reduce stress.Your vet may also prescribe painkillers and/or anti-inflammatory medications for short periods of time.","Cat");
    dbUserAnimal.addDiseaseDescription("Deafness","Deafness in cats may be congenital (present at birth) or acquired as a result of infection, trauma, toxins (including certain drugs), or degeneration of the ear.Deafness present at birth can be inherited or result from toxic or viral damage to the developing unborn kitten. A certain gene in cats causes white fur, blue eyes, and deafness; however, not all blue-eyed white cats are deaf. Deafness in this instance is due to degenerative changes that occur in the first week of life.","Cat");
    dbUserAnimal.addDiseaseDescription("Diabetes","Diabetes is the inability to produce enough insulin to balance blood sugar, or glucose, levels . Left untreated, it can lead to weight loss, loss of appetite, vomiting ,dehydration, severe depression, problems with motor function, coma, and even death.","Cat");
    dbUserAnimal.addDiseaseDescription("Distemper","Distemper in cats, also called feline panleukopenia (FPV), is a virus that is highly contagious and potentially life-threatening. The disease affects the blood cells in the intestinal tract, bone marrow, and stem cells. It also causes anemia and other viral and bacterial illnesses. Previously one of the most common causes of death in cats, distemper is now rare due to the effectiveness of vaccines. Kittens, pregnant cats, and cats with immune disorders are most likely to be infected with distemper.","Cat");
    dbUserAnimal.addDiseaseDescription("Fleas","Fleas are tiny, wingless insects that live on your cat’s body, feeding on blood and laying eggs in your cat’s fur, which then drop off throughout your home. A single flea can lay up to 2,000 eggs in its lifetime, and its full life cycle – from egg to larva to pupa to adult – can take place in a few weeks.Flea bites are painful and itchy for your cat, and they can cause a range of additional problems","Cat");
    dbUserAnimal.addDiseaseDescription("Flu","Cat flu is not usually serious in healthy cats. But it can be serious, and even fatal, in kittens and adult cats with underlying illnesses, so it's important to get your pet to the vet.It can cause: runny eyes and nose,sore throat,mouth ulcers,dribbling,sneezing,loss of voice and fever","Cat");
    dbUserAnimal.addDiseaseDescription("Hyperthyroidism","Hyperthyroidism is a common disease in cats, and mostly afflicts cats middle-aged and older. Also called thyrotoxicosis, hyperthyroidism is caused by an increase in production of thyroid hormones (known as T3 and T4) from an enlarged thyroid gland in a cat's neck.Mild to moderate diarrhoea and/or vomiting develop in some cats, and some will be noticeably intolerant of heat and seek out cooler places to sit. Some (especially advanced cases) may also pant when they are stressed, which is very unusual in cats","Cat");
    dbUserAnimal.addDiseaseDescription("Immunodeficiency","Feline immunodeficiency virus (FIV) is one of the most common and consequential infectious diseases of cats around the world. In infected cats, FIV attacks the immune system, leaving the cat vulnerable to many other infections. Although cats infected with FIV may appear normal for years, they eventually suffer from immune deficiency, which allows normally harmless bacteria, viruses, protozoa, and fungi found in the everyday environment to potentially cause severe illnesses.","Cat");
    dbUserAnimal.addDiseaseDescription("Leptospirosis","Leptospirosis is a disease caused by bacteria in the genus Leptospira. The disease affects virtually all mammals, including people, and has a broad range of effects, from mild infections with no signs to multiple-organ failure and death.Because leptospirosis can be transmitted to people, any caretakers should take appropriate precautions when handling known or suspected infected animals.","Cat");
    dbUserAnimal.addDiseaseDescription("Leukemia","Feline leukemia virus (FeLV) is a retrovirus that infects cats. FeLV can be transmitted from infected cats when the transfer of saliva or nasal secretions is involved. If not defeated by the animal's immune system, the virus weakens the cat's immune system which can lead to diseases which can be lethal.","Cat");
    dbUserAnimal.addDiseaseDescription("Lymphoma","Feline lymphoma is a malignant cancer of the lymphatic system, the exquisitely structured arrangement of internal organs and tissues that directly or indirectly influences virtually every aspect of a cat's physical existence.Progressive lack of appetite, lethargy and weight loss are among the most common problems showed by the cats affected.","Cat");
    dbUserAnimal.addDiseaseDescription("Lymphocytopenia","Lymphocytopenia is the condition of having an abnormally low level of lymphocytes in the blood.It is most commonly associated with endogenous (stress) or exogenous corticosteroid administration. The most likely cause is steroid-induced apoptosis of lymphocytes","Cat");
    dbUserAnimal.addDiseaseDescription("Mastocytoma","Mastocytoma is a mast cell tumor that is located in the skin. It can be inflamed, which is usually when you will notice that there is a tumor present.A variety of symptoms associated with this type of tumor include:vomiting,loss of appetite,itchiness,enlarged lymph nodes","Cat");
    dbUserAnimal.addDiseaseDescription("Rabies","Rabies is uncommon in domestic animals.When a cat does get rabies, it's usually from the bite of an infected wild animal. Raccoons, skunks, bats, and foxes are common rabies carriers. The more contact your cat has with wild animals, the higher the risk of their infection.","Cat");
    dbUserAnimal.addDiseaseDescription("Salmonella","Salmonella is a group of gram-negative bacteria of the family Enterobacteriaceae. Salmonella is mainly an intestinal pathogen, but can also cause systemic disease and can then be isolated from blood and various organs.Cats can become infected if contaminated raw material in the feed is inadequately heated.","Cat")
    dbUserAnimal.addDiseaseDescription("Tetanus","In cats, tetanus can take two forms.Localized tetanus is the more common form of tetanus that occurs in pets. Affected cats develop muscle rigidity (stiffness) in the limb or muscles closest to the wound. In addition to muscle rigidity, muscle tremors may also be seen. Localized tetanus can progress to generalized tetanus with time, although this does not always occur.Generalized tetanus affects widespread areas of the body.","Cat");
    dbUserAnimal.addDiseaseDescription("Thelaziasis","Thelaziasis is an infection caused by Thelazia callipaeda – a parasitic eye worm.Common symptoms are mild or severe inflammation of the inner lining of the eyelids, characterised by swelling and oozing; ocular ulcers and permanent blindness.Not all infected pets will show symptoms.","Cat");
    dbUserAnimal.addDiseaseDescription("Toxocariasis","Roundworms, and in particular Toxocara cati, are the most common intestinal parasites in cats and occur in cats of all ages throughout the world.Severe infections in kittens may result in: variable appetite or anorexia,vomiting (especially after feeding),diarrhoea alternated with constipation and growth disturbances","Cat");
    */

    //DOGS DISEASES 
    //dbUserAnimal.addDiseaseDescription(disease,description,"Dog");
    /*
    dbUserAnimal.addDiseaseDescription("Acromegaly","Acromegaly in dogs is an endocrine disorder.The increased secretion of somatotropin causes the abnormal overgrowth of bone, soft tissue and internal organs.Symptoms may include: hair loss,diabetes,hyperthyroidism,stiffness/rigidity,excessive urination,arthritis (inflammation of the joints) and heart failure","Dog");
    dbUserAnimal.addDiseaseDescription("Blastomycosis","Blastomycosis is a fungal infection in dogs caused by Blastomyces fungi.Respiratory disease is typical. Symptoms include coughing, trouble breathing, and congestion. Blastomycosis can affect many other areas of the body including the eyes (e.g. blindness, squinting, eye redness), skin (e.g. open, oozing sores; hard bumps under the skin), bones (e.g. leg pain, trouble walking), and lymph nodes (e.g. large swellings under the chin and in front of the shoulders).","Dog");
    dbUserAnimal.addDiseaseDescription("Cancer","Cancer in dogs is the leading cause of death among dogs.The most common symptoms are: abnormal or rapidly growing swellings, sores that do not heal, loss of appetite and weight loss, bleeding or discharge from body openings, difficulty in eating, lameness, difficulty in urinating or defecating","Dog");
    dbUserAnimal.addDiseaseDescription("Cataracts","Cataracts in dogs range in size, from a small dot to the complete lens. When a cataract is present, the opaque lens doesn't permit an image to form on the retina, resulting in vision loss. Light may still pass through the lens and your pet can still see light and dark.When a dog with cataracts is left untreated, they can become blind. ","Dog");
    dbUserAnimal.addDiseaseDescription("Clostridium","Clostridium in dogs is a bacterial infection that causes severe diarrhea.Clostridium will dwell within the soil and can be found in dogs that are not exhibiting any symptoms of distress. The bacteria will become problematic when there is an overgrowth and spores are formed. These spores then produce endotoxins. These toxins cause inflammation in the colon. Dogs of any age and of any breed can be affected by clostridium.","Dog");
    dbUserAnimal.addDiseaseDescription("Coronavirus","Canine coronavirus disease, known as CCoV, is a highly infectious intestinal infection in dogs, especially puppies. Canine coronavirus is usually short-lived but may cause considerable abdominal discomfort for a few days in infected dogs.It causes gastrointestinal problems.CCoV is not the same virus as SARS-CoV-2 that causes the novel coronavirus (COVID-19)","Dog");
    dbUserAnimal.addDiseaseDescription("Cystitis","Cystitis means inflammation of the bladder, and the term is used as a general description for any disease that causes inflammation.The most common clinical sign of cystitis is hematuria or blood in the urine. Cystitis also causes discomfort and pain. Dogs with cystitis may spend several minutes squatting and straining (dysuria) to produce only a small amount of urine, and they may urinate more frequently than normal (pollakiuria).","Dog");
    dbUserAnimal.addDiseaseDescription("Deafness","As dogs age, they can suffer hearing loss just as humans tend to. Generally, this is a gradual process, so it may be difficult to notice. The eardrums become less flexible, and sounds are not transmitted as effectively. Some dogs lose their hearing as a result of chronic ear infections. Still others may suffer a traumatic injury to the ear, resulting in hearing loss. Finally, some dogs are born deaf because of a genetic defect; this is called congenital deafness","Dog");
    dbUserAnimal.addDiseaseDescription("Diabetes","Diabetes is the inability to produce enough insulin to balance blood sugar, or glucose, levels . Left untreated, it can lead to weight loss, loss of appetite, vomiting ,dehydration, severe depression, problems with motor function, coma, and even death.","Dog");
    dbUserAnimal.addDiseaseDescription("Distemper","Canine distemper is a highly contagious virus caused by the paramyxovirus.Canine distemper affects the gastrointestinal, respiratory, skin, immune, and central nervous systems.Signs and symptoms of canine distemper include: fever, nasal discharge, eye discharge, lethargy, sneezing, coughing.","Dog");
    dbUserAnimal.addDiseaseDescription("Epilepsy","Epilepsy is a chronic condition that causes repeated seizures, and is the most common chronic (long-term) neurological disorder in dogs.Some dogs have more than one type of seizure, and not all seizures involve convulsions.Most epileptic fits usually happen quite suddenly without warning","Dog");
    dbUserAnimal.addDiseaseDescription("Fibrosarcoma","Fibrosarcomas are common tumors in dogs.A fibrosarcoma is a malignant tumor that develops from the uncontrolled overgrowth of cells called fibroblasts. Fibroblasts are the most common cells of the connective tissue in the body (the tissue that connects, supports, and binds or separates tissues and organs).Fibrosarcomas usually appear as a single, sometimes nodular, firm lump or bump on or under the skin, which at times may open (ulcerate), bleed, and become infected.","Dog");
    dbUserAnimal.addDiseaseDescription("Fleas","Fleas are tiny, wingless insects that live on your dog’s body, feeding on blood and laying eggs in your dog’s fur, which then drop off throughout your home. A single flea can lay up to 2,000 eggs in its lifetime, and its full life cycle – from egg to larva to pupa to adult – can take place in a few weeks.Flea bites are painful and itchy for your dog, and they can cause a range of additional problems","Dog");
    dbUserAnimal.addDiseaseDescription("Flu","Dog flu is not usually serious in healthy dogs. But it can be serious, and even fatal, in puppies and adult cats with underlying illnesses, so it's important to get your pet to the vet.It can cause: runny eyes and nose,sore throat,mouth ulcers,dribbling,sneezing,loss of voice and fever","Dog");
    dbUserAnimal.addDiseaseDescription("Hyperthyroidism","Hyperthyroidism is a common disease in dogs, and mostly afflicts dogs middle-aged and older. Also called thyrotoxicosis, hyperthyroidism is caused by an increase in production of thyroid hormones (known as T3 and T4) from an enlarged thyroid gland in a dog's neck.Mild to moderate diarrhoea and/or vomiting develop in some dogs, and some will be noticeably intolerant of heat and seek out cooler places to sit. Some (especially advanced cases) may also pant when they are stressed, which is very unusual in dogs","Dog");
    dbUserAnimal.addDiseaseDescription("Leptospirosis","Leptospirosis is a disease caused by bacteria in the genus Leptospira. The disease affects virtually all mammals, including people, and has a broad range of effects, from mild infections with no signs to multiple-organ failure and death.Because leptospirosis can be transmitted to people, any caretakers should take appropriate precautions when handling known or suspected infected animals.","Dog");
    dbUserAnimal.addDiseaseDescription("Leukemia","Leukemia in dogs is a form of cancer that results in an increased white blood cell count in the blood stream and bone marrow. It can be acute or chronic with the acute form being more malignant.Acute canine leukemia symptoms worsen quickly and must be treated immediately. It tends to affect middle-aged to older dogs after the age of six.","Dog");
    dbUserAnimal.addDiseaseDescription("Lymphoma","Lymphoma is one of the most common types of cancer diagnosed in dogs.It develops from specific cells of the immune system, called lymphocytes, that circulate through the blood. For that reason, lymphoma is generally considered a systemic disease (rather than a local one) and needs to be treated with systemic therapy.Lymphoma can affect many different organs. In over half of the dogs with this diagnosis, lymphoma will be present in their peripheral lymph nodes. Less commonly, it will occur in the chest cavity, intestines, skin or other organs.","Dog");
    dbUserAnimal.addDiseaseDescription("Melanomas","Melanoma is a tumor of melanocytes, or pigmented cells in the body. Malignant melanomas in dogs can be an aggressive cancer. We worry about both about the growth of the local tumor, as well as the potential for this tumor type to metastasize, or spread, to places like the local lymph nodes and lungs. Melanoma is the most common cancer found within the oral cavity in dogs.Melanomas in dogs often appear as pigmented masses that may start to bleed or ulcerate as they get larger.","Dog");
    dbUserAnimal.addDiseaseDescription("Osteosarcoma","Osteosarcoma in dogs is a primary bone tumour. It usually arises in the bones of the limbs but can develop in the bones of the skull, spine or ribcage and there are rare cases of this tumour arising in non-boney tissues like mammary glands and muscle.Osteosarcoma is most commonly found in large or giant breeds of dog.Osteosarcoma of the limb bones can be extremely painful and the typical presenting complaint for these dogs is that of an intermittent lameness.","Dog");
    dbUserAnimal.addDiseaseDescription("Pancreatitis","When the pancreas becomes inflamed, the condition is called pancreatitis. Pancreatitis commonly occurs in the dog. There is no age, sex, or breed predisposition. Pancreatitis may be acute or chronic.The most common clinical signs include nausea, vomiting, fever, lethargy, abdominal pain, diarrhea, and decreased appetite. During an attack, dogs may take a 'praying position', with their rear end up in the air while their front legs and head are lowered onto the floor.","Dog");
    dbUserAnimal.addDiseaseDescription("Parvovirus","Parvovirus is a highly contagious virus. It causes an infectious gastrointestinal (GI) illness in puppies and young dogs, and without treatment, it is potentially deadly.It can be transmitted in two ways. The first is by direct contact through the nose and mouth with infected poop, which can happen when a dog sniffs or licks a surface or another dog that has been contaminated with feces. Since puppies explore their world through smell and love to mouth things, it is easy to see how a curious puppy could contract the parvovirus.","Dog");
    dbUserAnimal.addDiseaseDescription("Pyometra","Pyometra is a very serious infection of the womb, also known as the 'uterus'. It's caused by the womb filling with pus and, if left untreated, it can lead to kidney failure, toxaemia, dehydration and, in some cases, death.Symptoms of pyometra include early warning signs of the animal feeling unwell, such as vomiting, refusal to eat, lethargy, increased thirst and frequent urination.She may also appear to be uncomfortable, because pyometra is a particularly painful condition for dogs","Dog");
    dbUserAnimal.addDiseaseDescription("Rabies","Rabies is uncommon in domestic animals.When a dog does get rabies, it's usually from the bite of an infected wild animal. Raccoons, skunks, bats, and foxes are common rabies carriers. The more contact your dog has with wild animals, the higher the risk of their infection.","Dog");
    dbUserAnimal.addDiseaseDescription("Tetanus","Tetanus is a very serious disease caused by a neurotoxin called tetanospasmin that is secreted by a bacterium known as Clostridium tetani. The neurotoxin affects the nervous system of dogs which can lead to painful stiffening and paralysis of the dog's jaw, neck, and other muscles.","Dog");
   */
    
});

afterAll(() => { //run with --detectOpenHandles
    
});

test("addds", () => {
    return expect(true).toBeTruthy();
});