import dbUserAnimal from "../firebase/Database/Functions/dbUserAnimal";

beforeAll(() => {

    // CATS DISEASES 
    /*
    //dbUserAnimal.addDiseaseDescription(disease,description,"Cat");
    dbUserAnimal.addDiseaseDescription("Acne","Feline acne is a problem seen in cats primarily involving the formation of blackheads accompanied by inflammation on the cat's chin and surrounding areas that can cause lesions, alopecia, and crusty sores.This problem can happen once, be reccurring, or even persistent throughout the cat's life.","Cat");
    dbUserAnimal.addDiseaseDescription("Aspergillosis","Aspergillosis is an infection, usually of the lungs, caused by the fungus Aspergillus. A ball of fungus fibers, blood clots, and white blood cells may form in the lungs or sinuses. Cats may have no symptoms or may cough up blood or have a fever, chest pain, and difficulty breathing.","Cat");
    dbUserAnimal.addDiseaseDescription("Cancer","Cancer in cats is the leading cause of death among cats. It is caused by uncontrolled cell growth, and affects a wide range of cell types and organs in the body. Feline cancer initially manifests as a lump or bump on any parts of the body. It rapidly grows in the affected cell; attaches itself to the tissue under the skin in that area; and, depending on the tumour, it can spread to other parts of the body.","Cat");
    dbUserAnimal.addDiseaseDescription("Coccidia","Coccidia is a protozoan that infects the intestinal tract of cats and other species and causes coccidiosis. It is a single-celled organism and while it isn't a worm or an egg, it is still a type of intestinal parasite. Signs of Coccidia in cats are : diarrhea,crying when defecating,sensitive when its belly is pressed,dehydration with sunken eyes and skin tenting,vomiting,loss of appetite and lethargy","Cat");
    dbUserAnimal.addDiseaseDescription("Coronavirus","Feline Coronavirus (FCoV) is a common viral infection in cats. It generally causes asymptomatic infection, but can cause mild diarrhea. As yet poorly understood changes in the virus can give rise to mutants that lead to the development of feline infectious peritonitis.Most cats infected with a FCoV eliminate virus following infection, but some cats may develop a persistent infection. These cats are generally asymptomatic, can shed large amounts of virus in feces, and serve as a continual source of infection for other cats in the environment.","Cat");
    dbUserAnimal.addDiseaseDescription("Cystitis","Cystitis in cats, also known as FIC (Feline Idiopathic Cystitis) affects a cat’s bladder and urinary tract and is usually triggered by stress.Treating Cystitis in cats usually involves a combination of changes both to the cat’s diet and to their home environment in order to reduce stress.Your vet may also prescribe painkillers and/or anti-inflammatory medications for short periods of time.","Cat");
    dbUserAnimal.addDiseaseDescription("Deafness","Deafness in cats may be congenital (present at birth) or acquired as a result of infection, trauma, toxins (including certain drugs), or degeneration of the ear.Deafness present at birth can be inherited or result from toxic or viral damage to the developing unborn kitten. A certain gene in cats causes white fur, blue eyes, and deafness; however, not all blue-eyed white cats are deaf. Deafness in this instance is due to degenerative changes that occur in the first week of life.","Cat");
    dbUserAnimal.addDiseaseDescription("Diabetes","Diabetes is the inability to produce enough insulin to balance blood sugar, or glucose, levels . Left untreated, it can lead to weight loss, loss of appetite, vomiting ,dehydration, severe depression, problems with motor function, coma, and even death.","Cat");
    dbUserAnimal.addDiseaseDescription("Distemper","Distemper in cats, also called feline panleukopenia (FPV), is a virus that is highly contagious and potentially life-threatening. The disease affects the blood cells in the intestinal tract, bone marrow, and stem cells. It also causes anemia and other viral and bacterial illnesses. Previously one of the most common causes of death in cats, distemper is now rare due to the effectiveness of vaccines. Kittens, pregnant cats, and cats with immune disorders are most likely to be infected with distemper.","Cat");
    dbUserAnimal.addDiseaseDescription("Fleas","Fleas are tiny, wingless insects that live on your cat’s body, feeding on blood and laying eggs in your cat’s fur, which then drop off throughout your home. A single flea can lay up to 2,000 eggs in its lifetime, and its full life cycle – from egg to larva to pupa to adult – can take place in a few weeks.Flea bites are painful and itchy for your cat, and they can cause a range of additional problems","Cat");
    dbUserAnimal.addDiseaseDescription("Flu","Cat flu is not usually serious in healthy cats. But it can be serious, and even fatal, in kittens and adult cats with underlying illnesses, so it's important to get your pet to the vet.It can cause: runny eyes and nose,sore throat,mouth ulcers,dribbling,sneezing,loss of voice and fever","Cat");
    dbUserAnimal.addDiseaseDescription("Hyperthyroidism","Hyperthyroidism is a common disease in cats, and mostly afflicts cats middle-aged and older. Also called thyrotoxicosis, hyperthyroidism is caused by an increase in production of thyroid hormones (known as T3 and T4) from an enlarged thyroid gland in a cat's neck.Mild to moderate diarrhoea and/or vomiting develop in some cats, and some will be noticeably intolerant of heat and seek out cooler places to sit. Some (especially advanced cases) may also pant when they are stressed, which is very unusual in cats","Cat");
    dbUserAnimal.addDiseaseDescription("Immunodeficiency","Feline immunodeficiency virus (FIV) is one of the most common and consequential infectious diseases of cats around the world. In infected cats, FIV attacks the immune system, leaving the cat vulnerable to many other infections. Although cats infected with FIV may appear normal for years, they eventually suffer from immune deficiency, which allows normally harmless bacteria, viruses, protozoa, and fungi found in the everyday environment to potentially cause severe illnesses.","Cat");
    dbUserAnimal.addDiseaseDescription("Leptospirosis","Leptospirosis is a disease caused by bacteria in the genus Leptospira. The disease affects virtually all mammals, including people, and has a broad range of effects, from mild infections with no signs to multiple-organ failure and death.Because leptospirosis can be transmitted to people, any caretakers should take appropriate precautions when handling known or suspected infected animals.","Cat");
    dbUserAnimal.addDiseaseDescription("Leukemia","Feline leukemia virus (FeLV) is a retrovirus that infects cats. FeLV can be transmitted from infected cats when the transfer of saliva or nasal secretions is involved. If not defeated by the animal's immune system, the virus weakens the cat's immune system which can lead to diseases which can be lethal.","Cat");
    dbUserAnimal.addDiseaseDescription("Lymphoma","Feline lymphoma is a malignant cancer of the lymphatic system, the exquisitely structured arrangement of internal organs and tissues that directly or indirectly influences virtually every aspect of a cat's physical existence.Progressive lack of appetite, lethargy and weight loss are among the most common problems showed by the cats affected.","Cat");
    dbUserAnimal.addDiseaseDescription("Lymphocytopenia","Lymphocytopenia is the condition of having an abnormally low level of lymphocytes in the blood.It is most commonly associated with endogenous (stress) or exogenous corticosteroid administration. The most likely cause is steroid-induced apoptosis of lymphocytes","Cat");
    dbUserAnimal.addDiseaseDescription("Mastocytoma","Mastocytoma is a mast cell tumor that is located in the skin. It can be inflamed, which is usually when you will notice that there is a tumor present.A variety of symptoms associated with this type of tumor include:vomiting,loss of appetite,itchiness,enlarged lymph nodes","Cat");
    dbUserAnimal.addDiseaseDescription("Rabies","Rabies is uncommon in domestic animals.When a cat does get rabies, it's usually from the bite of an infected wild animal. Raccoons, skunks, bats, and foxes are common rabies carriers. The more contact your cat has with wild animals, the higher the risk of their infection.","Cat");
    dbUserAnimal.addDiseaseDescription("Salmonella","Salmonella is a group of gram-negative bacteria of the family Enterobacteriaceae. Salmonella is mainly an intestinal pathogen, but can also cause systemic disease and can then be isolated from blood and various organs.Cats can become infected if contaminated raw material in the feed is inadequately heated.","Cat")
    dbUserAnimal.addDiseaseDescription("Tetanus","In cats, tetanus can take two forms.Localized tetanus is the more common form of tetanus that occurs in pets. Affected cats develop muscle rigidity (stiffness) in the limb or muscles closest to the wound. In addition to muscle rigidity, muscle tremors may also be seen. Localized tetanus can progress to generalized tetanus with time, although this does not always occur.Generalized tetanus affects widespread areas of the body.","Cat");
    dbUserAnimal.addDiseaseDescription("Thelaziasis","Thelaziasis is an infection caused by Thelazia callipaeda – a parasitic eye worm.Common symptoms are mild or severe inflammation of the inner lining of the eyelids, characterised by swelling and oozing; ocular ulcers and permanent blindness.Not all infected pets will show symptoms.","Cat");
    dbUserAnimal.addDiseaseDescription("Toxocariasis","Roundworms, and in particular Toxocara cati, are the most common intestinal parasites in cats and occur in cats of all ages throughout the world.Severe infections in kittens may result in: variable appetite or anorexia,vomiting (especially after feeding),diarrhoea alternated with constipation and growth disturbances","Cat");
    */
   
});

afterAll(() => { //run with --detectOpenHandles
    
});

test("addds", () => {
    return expect(true).toBeTruthy();
});