import dbUserAnimal from "../firebase/Database/Functions/dbUserAnimal";
import dbFeed from "../firebase/Database/Functions/dbFeed";
import dbUser from "../firebase/Database/Functions/dbUser";
import Feed from "../firebase/Database/Objects/Feed";
import UserAnimal from "../firebase/Database/Objects/UserAnimal";

beforeAll(() => {

    // CATS DISEASES 
    /*
    //dbUserAnimal.addDiseaseDescription(disease,description,"Cat");
    dbUserAnimal.addDiseaseDescription("Acne","Feline acne is a problem seen in cats primarily involving the formation of blackheads accompanied by inflammation on the cat's chin and surrounding areas that can cause lesions, alopecia, and crusty sores.This problem can happen once, be reccurring, or even persistent throughout the cat's life.","Cat");
    dbUserAnimal.addDiseaseDescription("Aspergillosis","Aspergillosis is an infection, usually of the lungs, caused by the fungus Aspergillus. A ball of fungus fibers, blood clots, and white blood cells may form in the lungs or sinuses. Cats may have no symptoms or may cough up blood or have a fever, chest pain, and difficulty breathing.","Cat");
    dbUserAnimal.addDiseaseDescription("Blindness","Many obstacles and situations are not dangerous if your four-legged buddy can see, but become hazardous if they are blind. Blindness may result as a symptom of a different disorder, such as diabetes, or it could be from injury, and sometimes it is due to a hereditary disease you did not know your cat had.","Cat");
    dbUserAnimal.addDiseaseDescription("Cancer","Cancer in cats is the leading cause of death among cats. It is caused by uncontrolled cell growth, and affects a wide range of cell types and organs in the body. Feline cancer initially manifests as a lump or bump on any parts of the body. It rapidly grows in the affected cell; attaches itself to the tissue under the skin in that area; and, depending on the tumour, it can spread to other parts of the body.","Cat");
    dbUserAnimal.addDiseaseDescription("Coccidia","Coccidia is a protozoan that infects the intestinal tract of cats and other species and causes coccidiosis. It is a single-celled organism and while it isn't a worm or an egg, it is still a type of intestinal parasite. Signs of Coccidia in cats are : diarrhea,crying when defecating,sensitive when its belly is pressed,dehydration with sunken eyes and skin tenting,vomiting,loss of appetite and lethargy","Cat");
    dbUserAnimal.addDiseaseDescription("Coronavirus","Feline Coronavirus (FCoV) is a common viral infection in cats. It generally causes asymptomatic infection, but can cause mild diarrhea. As yet poorly understood changes in the virus can give rise to mutants that lead to the development of feline infectious peritonitis.Most cats infected with a FCoV eliminate virus following infection, but some cats may develop a persistent infection.FCoV is not the same virus as SARS-CoV-2 that causes the novel coronavirus (COVID-19)","Cat");
    dbUserAnimal.addDiseaseDescription("Cystitis","Cystitis in cats, also known as FIC (Feline Idiopathic Cystitis) affects a cat’s bladder and urinary tract and is usually triggered by stress.Treating Cystitis in cats usually involves a combination of changes both to the cat’s diet and to their home environment in order to reduce stress.Your vet may also prescribe painkillers and/or anti-inflammatory medications for short periods of time.","Cat");
    dbUserAnimal.addDiseaseDescription("Deafness","Deafness in cats may be congenital (present at birth) or acquired as a result of infection, trauma, toxins (including certain drugs), or degeneration of the ear.Deafness present at birth can be inherited or result from toxic or viral damage to the developing unborn kitten. A certain gene in cats causes white fur, blue eyes, and deafness; however, not all blue-eyed white cats are deaf. Deafness in this instance is due to degenerative changes that occur in the first week of life.","Cat");
    dbUserAnimal.addDiseaseDescription("Diabetes","Diabetes is the inability to produce enough insulin to balance blood sugar, or glucose, levels . Left untreated, it can lead to weight loss, loss of appetite, vomiting ,dehydration, severe depression, problems with motor function, coma, and even death.","Cat");
    dbUserAnimal.addDiseaseDescription("Distemper","Distemper in cats, also called feline panleukopenia (FPV), is a virus that is highly contagious and potentially life-threatening. The disease affects the blood cells in the intestinal tract, bone marrow, and stem cells. It also causes anemia and other viral and bacterial illnesses. Previously one of the most common causes of death in cats, distemper is now rare due to the effectiveness of vaccines. Kittens, pregnant cats, and cats with immune disorders are most likely to be infected with distemper.","Cat");
    dbUserAnimal.addDiseaseDescription("Fleas","Fleas are tiny, wingless insects that live on your cat’s body, feeding on blood and laying eggs in your cat’s fur, which then drop off throughout your home. A single flea can lay up to 2,000 eggs in its lifetime, and its full life cycle – from egg to larva to pupa to adult – can take place in a few weeks.Flea bites are painful and itchy for your cat, and they can cause a range of additional problems","Cat");
    dbUserAnimal.addDiseaseDescription("Flu","Cat flu is not usually serious in healthy cats. But it can be serious, and even fatal, in kittens and adult cats with underlying illnesses, so it's important to get your pet to the vet.It can cause: runny eyes and nose,sore throat,mouth ulcers,dribbling,sneezing,loss of voice and fever","Cat");
    dbUserAnimal.addDiseaseDescription("Hyperthyroidism","Hyperthyroidism is a common disease in cats, and mostly afflicts cats middle-aged and older. Also called thyrotoxicosis, hyperthyroidism is caused by an increase in production of thyroid hormones (known as T3 and T4) from an enlarged thyroid gland in a cat's neck.Mild to moderate diarrhoea and/or vomiting develop in some cats, and some will be noticeably intolerant of heat and seek out cooler places to sit. Some (especially advanced cases) may also pant when they are stressed, which is very unusual in cats","Cat");
    dbUserAnimal.addDiseaseDescription("Immunodeficiency","Feline immunodeficiency virus (FIV) is one of the most common and consequential infectious diseases of cats around the world. In infected cats, FIV attacks the immune system, leaving the cat vulnerable to many other infections. Although cats infected with FIV may appear normal for years, they eventually suffer from immune deficiency, which allows normally harmless bacteria, viruses, protozoa, and fungi found in the everyday environment to potentially cause severe illnesses.","Cat");
    dbUserAnimal.addDiseaseDescription("Leptospirosis","Leptospirosis is a disease caused by bacteria in the genus Leptospira. The disease affects virtually all mammals, including people, and has a broad range of effects, from mild infections with no signs to multiple-organ failure and death.Because leptospirosis can be transmitted to people, any caretakers should take appropriate precautions when handling known or suspected infected animals.","Cat");
    dbUserAnimal.addDiseaseDescription("Leukemia","Feline leukemia virus (FeLV) is a retrovirus that infects cats. FeLV can be transmitted from infected cats when the transfer of saliva or nasal secretions is involved. If not defeated by the animal's immune system, the virus weakens the cat's immune system which can lead to diseases which can be lethal.","Cat");
    dbUserAnimal.addDiseaseDescription("Lymphoma","Feline lymphoma is a malignant cancer of the lymphatic system, the exquisitely structured arrangement of internal organs and tissues that directly or indirectly influences virtually every aspect of a cat's physical existence.Progressive lack of appetite, lethargy and weight loss are among the most common problems showed by the cats affected.","Cat");
    dbUserAnimal.addDiseaseDescription("Lymphocytopenia","Lymphocytopenia is the condition of having an abnormally low level of lymphocytes in the blood.It is most commonly associated with endogenous (stress) or exogenous corticosteroid administration. The most likely cause is steroid-induced apoptosis of lymphocytes","Cat");
    dbUserAnimal.addDiseaseDescription("Mastocytoma","Mastocytoma is a mast cell tumor that is located in the skin. It can be inflamed, which is usually when you will notice that there is a tumor present.A variety of symptoms associated with this type of tumor include:vomiting,loss of appetite,itchiness,enlarged lymph nodes","Cat");
    dbUserAnimal.addDiseaseDescription("Rabies","Rabies is uncommon in domestic animals.When a cat does get rabies, it's usually from the bite of an infected wild animal. Raccoons, skunks, bats, and foxes are common rabies carriers. The more contact your cat has with wild animals, the higher the risk of their infection.","Cat");
    dbUserAnimal.addDiseaseDescription("Salmonella","Salmonella is a group of gram-negative bacteria of the family Enterobacteriaceae. Salmonella is mainly an intestinal pathogen, but can also cause systemic disease and can then be isolated from blood and various organs.Cats can become infected if contaminated raw material in the feed is inadequately heated.","Cat")
    dbUserAnimal.addDiseaseDescription("Tetanus","In cats, tetanus can take two forms.Localized tetanus is the more common form of tetanus that occurs in pets. Affected cats develop muscle rigidity (stiffness) in the limb or muscles closest to the wound. In addition to muscle rigidity, muscle tremors may also be seen. Localized tetanus can progress to generalized tetanus with time, although this does not always occur.Generalized tetanus affects widespread areas of the body.","Cat");
    dbUserAnimal.addDiseaseDescription("Thelaziasis","Thelaziasis is an infection caused by Thelazia callipaeda – a parasitic eye worm.Common symptoms are mild or severe inflammation of the inner lining of the eyelids, characterised by swelling and oozing; ocular ulcers and permanent blindness.Not all infected pets will show symptoms.","Cat");
    dbUserAnimal.addDiseaseDescription("Toxocariasis","Roundworms, and in particular Toxocara cati, are the most common intestinal parasites in cats and occur in cats of all ages throughout the world.Severe infections in kittens may result in: variable appetite or anorexia,vomiting (especially after feeding),diarrhoea alternated with constipation and growth disturbances","Cat");
    

    //DOGS DISEASES 
    //dbUserAnimal.addDiseaseDescription(disease,description,"Dog");
    
    dbUserAnimal.addDiseaseDescription("Acromegaly","Acromegaly in dogs is an endocrine disorder.The increased secretion of somatotropin causes the abnormal overgrowth of bone, soft tissue and internal organs.Symptoms may include: hair loss,diabetes,hyperthyroidism,stiffness/rigidity,excessive urination,arthritis (inflammation of the joints) and heart failure","Dog");
    dbUserAnimal.addDiseaseDescription("Blastomycosis","Blastomycosis is a fungal infection in dogs caused by Blastomyces fungi.Respiratory disease is typical. Symptoms include coughing, trouble breathing, and congestion. Blastomycosis can affect many other areas of the body including the eyes (e.g. blindness, squinting, eye redness), skin (e.g. open, oozing sores; hard bumps under the skin), bones (e.g. leg pain, trouble walking), and lymph nodes (e.g. large swellings under the chin and in front of the shoulders).","Dog");
    dbUserAnimal.addDiseaseDescription("Blindness","Many obstacles and situations are not dangerous if your four-legged buddy can see, but become hazardous if they are blind. Blindness may result as a symptom of a different disorder, such as diabetes, or it could be from injury, and sometimes it is due to a hereditary disease you did not know your dog had.","Dog");
    dbUserAnimal.addDiseaseDescription("Cancer","Cancer in dogs is the leading cause of death among dogs.The most common symptoms are: abnormal or rapidly growing swellings, sores that do not heal, loss of appetite and weight loss, bleeding or discharge from body openings, difficulty in eating, lameness, difficulty in urinating or defecating","Dog");
    dbUserAnimal.addDiseaseDescription("Cataracts","Cataracts in dogs range in size, from a small dot to the complete lens. When a cataract is present, the opaque lens doesn't permit an image to form on the retina, resulting in vision loss. Light may still pass through the lens and your pet can still see light and dark.When a dog with cataracts is left untreated, they can become blind. ","Dog");
    dbUserAnimal.addDiseaseDescription("Clostridium","Clostridium in dogs is a bacterial infection that causes severe diarrhea.Clostridium will dwell within the soil and can be found in dogs that are not exhibiting any symptoms of distress. The bacteria will become problematic when there is an overgrowth and spores are formed. These spores then produce endotoxins. These toxins cause inflammation in the colon. Dogs of any age and of any breed can be affected by clostridium.","Dog");
    dbUserAnimal.addDiseaseDescription("Coronavirus","Canine coronavirus disease, known as CCoV, is a highly infectious intestinal infection in dogs, especially puppies. Canine coronavirus is usually short-lived but may cause considerable abdominal discomfort for a few days in infected dogs.It causes gastrointestinal problems.CCoV is not the same virus as SARS-CoV-2 that causes the novel coronavirus (COVID-19)","Dog");
    dbUserAnimal.addDiseaseDescription("Cystitis","Cystitis means inflammation of the bladder, and the term is used as a general description for any disease that causes inflammation.The most common clinical sign of cystitis is hematuria or blood in the urine. Cystitis also causes discomfort and pain. Dogs with cystitis may spend several minutes squatting and straining (dysuria) to produce only a small amount of urine, and they may urinate more frequently than normal (pollakiuria).","Dog");
    dbUserAnimal.addDiseaseDescription("Deafness","As dogs age, they can suffer hearing loss just as humans tend to. Generally, this is a gradual process, so it may be difficult to notice. The eardrums become less flexible, and sounds are not transmitted as effectively. Some dogs lose their hearing as a result of chronic ear infections. Still others may suffer a traumatic injury to the ear, resulting in hearing loss. Finally, some dogs are born deaf because of a genetic defect; this is called congenital deafness","Dog");
    dbUserAnimal.addDiseaseDescription("Diabetes","Diabetes is the inability to produce enough insulin to balance blood sugar, or glucose, levels . Left untreated, it can lead to weight loss, loss of appetite, vomiting ,dehydration, severe depression, problems with motor function, coma, and even death.","Dog");
    dbUserAnimal.addDiseaseDescription("Distemper","Canine distemper is a highly contagious virus caused by the paramyxovirus.Canine distemper affects the gastrointestinal, respiratory, skin, immune, and central nervous systems.Signs and symptoms of canine distemper include: fever, nasal discharge, eye discharge, lethargy, sneezing, coughing.","Dog");
    dbUserAnimal.addDiseaseDescription("Epilepsy","Epilepsy is a chronic condition that causes repeated seizures, and is the most common chronic (long-term) neurological disorder in dogs.Some dogs have more than one type of seizure, and not all seizures involve convulsions.Most epileptic fits usually happen quite suddenly without warning","Dog");
    dbUserAnimal.addDiseaseDescription("Fibrosarcoma","Fibrosarcomas are common tumors in dogs.A fibrosarcoma is a malignant tumor that develops from the uncontrolled overgrowth of cells called fibroblasts. Fibroblasts are the most common cells of the connective tissue in the body (the tissue that connects, supports, and binds or separates tissues and organs).Fibrosarcomas usually appear as a single, sometimes nodular, firm lump or bump on or under the skin, which at times may open (ulcerate), bleed, and become infected.","Dog");
    dbUserAnimal.addDiseaseDescription("Fleas","Fleas are tiny, wingless insects that live on your dog’s body, feeding on blood and laying eggs in your dog’s fur, which then drop off throughout your home. A single flea can lay up to 2,000 eggs in its lifetime, and its full life cycle – from egg to larva to pupa to adult – can take place in a few weeks.Flea bites are painful and itchy for your dog, and they can cause a range of additional problems","Dog");
    dbUserAnimal.addDiseaseDescription("Flu","Dog flu is not usually serious in healthy dogs. But it can be serious, and even fatal, in puppies and adult cats with underlying illnesses, so it's important to get your pet to the vet.It can cause: runny eyes and nose,sore throat,mouth ulcers,dribbling,sneezing,loss of voice and fever","Dog");
    dbUserAnimal.addDiseaseDescription("Hyperthyroidism","Hyperthyroidism is a common disease in dogs, and mostly afflicts dogs middle-aged and older. Also called thyrotoxicosis, hyperthyroidism is caused by an increase in production of thyroid hormones (known as T3 and T4) from an enlarged thyroid gland in a dog's neck.Mild to moderate diarrhoea and/or vomiting develop in some dogs, and some will be noticeably intolerant of heat and seek out cooler places to sit. Some (especially advanced cases) may also pant when they are stressed, which is very unusual in dogs","Dog");
    dbUserAnimal.addDiseaseDescription("Leptospirosis","Leptospirosis is a disease caused by bacteria in the genus Leptospira. The disease affects virtually all mammals, including people, and has a broad range of effects, from mild infections with no signs to multiple-organ failure and death.Because leptospirosis can be transmitted to people, any caretakers should take appropriate precautions when handling known or suspected infected animals.","Dog");
    dbUserAnimal.addDiseaseDescription("Leukemia","Leukemia in dogs is a form of cancer that results in an increased white blood cell count in the blood stream and bone marrow. It can be acute or chronic with the acute form being more malignant.Acute canine leukemia symptoms worsen quickly and must be treated immediately. It tends to affect middle-aged to older dogs after the age of six.","Dog");
    dbUserAnimal.addDiseaseDescription("Lymphoma","Lymphoma is one of the most common types of cancer diagnosed in dogs.It develops from specific cells of the immune system, called lymphocytes, that circulate through the blood. For that reason, lymphoma is generally considered a systemic disease (rather than a local one) and needs to be treated with systemic therapy.Lymphoma can affect many different organs. In over half of the dogs with this diagnosis, lymphoma will be present in their peripheral lymph nodes. Less commonly, it will occur in the chest cavity, intestines, skin or other organs.","Dog");
    dbUserAnimal.addDiseaseDescription("Melanomas","Melanoma is a tumor of melanocytes, or pigmented cells in the body. Malignant melanomas in dogs can be an aggressive cancer. We worry about both about the growth of the local tumor, as well as the potential for this tumor type to metastasize, or spread, to places like the local lymph nodes and lungs. Melanoma is the most common cancer found within the oral cavity in dogs.Melanomas in dogs often appear as pigmented masses that may start to bleed or ulcerate as they get larger.","Dog");
    dbUserAnimal.addDiseaseDescription("Osteosarcoma","Osteosarcoma in dogs is a primary bone tumour. It usually arises in the bones of the limbs but can develop in the bones of the skull, spine or ribcage and there are rare cases of this tumour arising in non-boney tissues like mammary glands and muscle.Osteosarcoma is most commonly found in large or giant breeds of dog.Osteosarcoma of the limb bones can be extremely painful and the typical presenting complaint for these dogs is that of an intermittent lameness.","Dog");
    dbUserAnimal.addDiseaseDescription("Pancreatitis","When the pancreas becomes inflamed, the condition is called pancreatitis. Pancreatitis commonly occurs in the dog. There is no age, sex, or breed predisposition. Pancreatitis may be acute or chronic.The most common clinical signs include nausea, vomiting, fever, lethargy, abdominal pain, diarrhea, and decreased appetite. During an attack, dogs may take a 'praying position', with their rear end up in the air while their front legs and head are lowered onto the floor.","Dog");
    dbUserAnimal.addDiseaseDescription("Parvovirus","Parvovirus is a highly contagious virus. It causes an infectious gastrointestinal (GI) illness in puppies and young dogs, and without treatment, it is potentially deadly.It can be transmitted in two ways. The first is by direct contact through the nose and mouth with infected poop, which can happen when a dog sniffs or licks a surface or another dog that has been contaminated with feces. Since puppies explore their world through smell and love to mouth things, it is easy to see how a curious puppy could contract the parvovirus.","Dog");
    dbUserAnimal.addDiseaseDescription("Pyometra","Pyometra is a very serious infection of the womb, also known as the 'uterus'. It's caused by the womb filling with pus and, if left untreated, it can lead to kidney failure, toxaemia, dehydration and, in some cases, death.Symptoms of pyometra include early warning signs of the animal feeling unwell, such as vomiting, refusal to eat, lethargy, increased thirst and frequent urination.She may also appear to be uncomfortable, because pyometra is a particularly painful condition for dogs","Dog");
    dbUserAnimal.addDiseaseDescription("Rabies","Rabies is uncommon in domestic animals.When a dog does get rabies, it's usually from the bite of an infected wild animal. Raccoons, skunks, bats, and foxes are common rabies carriers. The more contact your dog has with wild animals, the higher the risk of their infection.","Dog");
    dbUserAnimal.addDiseaseDescription("Tetanus","Tetanus is a very serious disease caused by a neurotoxin called tetanospasmin that is secreted by a bacterium known as Clostridium tetani. The neurotoxin affects the nervous system of dogs which can lead to painful stiffening and paralysis of the dog's jaw, neck, and other muscles.","Dog");
    

    // CAT FEEDS   //None --- mongrels (meticci)
    
    dbFeed.addPetFeed("Cat", "Breed", 0,"Bombay", "Your Bombay’s Health", "Like all cats, Bombays are susceptible to bacterial and viral infections such as panleukopenia, calicivirus, rhinotracheitis, and rabies, which are preventable through vaccination. The risk of your cat contracting these diseases is high, so the corresponding vaccines are called “core” vaccines, which are highly recommended for all cats. In addition, vaccines are available to offer protection from other dangerous diseases like feline leukemia virus (FeLV).");
    dbFeed.addPetFeed("Cat", "Breed", 1,"Bombay", "Bombay: What a Unique Breed!", "Your cat is special! She senses your moods, is curious about your day, and has purred her way into your heart. This breed is full of personality: she is an inquisitive and lap-loving companion that can be demanding of attention but is well suited to active homes with multiple pets! Main traits: friendly, extroverted personality, may meow constantly to get your attention.");
    dbFeed.addPetFeed("Cat", "Breed", 0,"Bombay", "Your Bombay’s Health", "Bombay are unfortunately really prone to obesity. Although they are in general really active, they can become overweight easily if not exercised regularly. Pay attention that excess weight is one of the most influential factors in the development of arthritis, diabetes, and other life-threatening diseases");
    dbFeed.addPetFeed("Cat", "Breed", 1,"Bombay", "Bombay: What a Unique Breed!", "The Bombay is a hybrid breed that was developed in Kentucky from crossings between Sable Burmese and Black American Shorthairs. This sleek all black feline resembles a miniature black panther with golden or copper eyes and has earned the nickname “parlor panther.”Bombays are noted to be calm and frequently found lounging in the warmest spots of the house. The Bombay is outgoing and expressive; they will often be the first to welcome and entertain guests.");
    
    dbFeed.addPetFeed("Cat", "Breed", 0,"Siamese", "Your Siamese’s Health", "Lymphoma is a type of cancer that afflicts Siamese more than other breeds. It is a malignant cancer of the lymphatic system. Lymphoma is a very treatable form of cancer, and chemotherapy in cats has shown an excellent success rate for recovery. Treatment can be costly, however, and is a lifelong commitment. Luckily, lymphoma is one of the few types of cancer that can often be detected with a blood test, so we recommend a complete blood count twice yearly for your adult cat.");
    dbFeed.addPetFeed("Cat", "Breed", 0,"Siamese", "Your Siamese’s Health", "While the vast majority of felines prefer a solitary lifestyle, some Siamese can form unhealthy and excessive attachments to their owners. They can become so attached that when their human counterparts aren't around, they quickly become anxious or bored, leading to destructive behaviors such as paper shredding, vocalization, or litter box amnesia. To avoid the vices of boredom, make sure your cat has plenty of special toys or food puzzles to keep his mind and body active while he is left alone.");
    dbFeed.addPetFeed("Cat", "Breed", 1,"Siamese", "Siamese: What a Unique Breed!", "One of the peculiar features of Siamese cats is that they are extremely talkative. They earned the nickname “Meezer” for her overly vocal tendencies. She has a loud, low-pitched voice that could be compared to the cries of a human baby. She is demanding of both conversation and attention—and always has to have the last word.");
    dbFeed.addPetFeed("Cat", "Breed", 1,"Siamese", "Siamese: What a Unique Breed!", "Siamese Cat history shows they originated in Siam, what is now Thailand. For years, it was once believed they came from Egypt due to the resemblance to the Egyptian Cat Goddess, Bastet. It is believed the Royal Family of Siam owned Siamese cats and used them to guard the ancient temples. According to Siamese Cat history, only royalty or noblemen were allowed to own them, and their cats served as spirit guardians.");

    dbFeed.addPetFeed("Cat","Age",0,"Young","Discipline your young cat","Whenever possible, give treats, praise, and attention to your cat if it is behaving nicely. If you notice it lying next to something it used to chew, reward it. If you notice it scratching the scratching pole instead of your sofa, reward it. Your cat will quickly learn the difference between good and bad behavior.");
    dbFeed.addPetFeed("Cat","Age",0,"Young","Don’t Treat Your Kitten Like an Adult Cat","Just as a human infant has vastly different needs than a teenager, a kitten will have care requirements distinct from those of a fully matured cat. In addition, you should consider a kitten’s various stages of development when caring for her.The socialization and training your cat receives during kittenhood will affect how well she will likely interact with people and other animals when she’s older.");
    dbFeed.addPetFeed("Cat","Age",1,"Young","Feed your young cat","Felines are natural carnivores and do not intentionally consume large quantities of carbohydrates. The domestic cat's liver has adapted to the lack of carbohydrates in the diet by using amino acids to produce glucose to fuel the brain and other tissues.Studies have shown that carbohydrate digestion in young kittens is much less effective than that of a mature feline with a developed gastrointestinal tract. Highly digestible carbohydrates can be found in commercial kitten food.");
    dbFeed.addPetFeed("Cat","Age",1,"Young","Feed your young cat","Cats require taurine, an essential amino acid, for heart and eye health. The food you choose should be balanced for the life stage of your cat or kitten. Properly balanced foods will contain taurine. You will need to provide fresh, clean water at all times, and wash and refill your cat's water bowls daily.");
    
    dbFeed.addPetFeed("Cat","Size",0,"Small","How high can a small-sized cat jump?","Although the average healthy cat is able to jump up to six times their height in one jump – this is around 8 foot or 2.4 metres. So not be too much surprised if you'll find your small cat on top of your shelf!");
    dbFeed.addPetFeed("Cat","Size",1,"Small","Where could my cat be hiding?","Don't worry if you don't find your pet immediately, cats love hiding places, especially small cats! They love to tuck themselves into small spaces in your closet, under your bed, or in a cardboard box or paper bag left lying on the floor. Sometimes it can take a long time and a keen eye to find your cat when she is hiding. ");
    dbFeed.addPetFeed("Cat","Size",1,"Small","How much should a small-sized cat eat a day?","That's a question best answered by a professional, though recommendations range between 24 to 35 calories a day per pound, to keep cats at a normal, healthy weight.");
    // size small 1 

    //DOG FEEDS

    // GENERAL FEEDS

    dbFeed.addPetFeed("Dog", "Breed", 0,"Labrador", "Your Labrador’s Health", "A number of different musculoskeletal problems have been reported in Labrador Retrievers. While it may seem overwhelming, each condition can be diagnosed and treated to prevent undue pain and suffering. With diligent observation at home and knowledge about the diseases that may affect your friend’s bones, joints, or muscles you will be able to take great care of him throughout his life.");
    dbFeed.addPetFeed("Dog", "Breed", 1,"Labrador", "Labrador: What a Unique Breed!", "Labrador are one of the best breeds for SAR(Search And Rescue). You have probably seen SAR dogs them on TV, or even in the flesh, dogs that specialize in finding people in need if they get lost in the woods or following an avalanche. They are perfect for these types of activity because of their strong lengs and bodies and also because of their friendly temperament.");
    dbFeed.addPetFeed("Dog", "Breed", 0,"Labrador", "Your Labrador’s Health", "Not many things have as dramatic an impact on your dog’s quality of life as the proper functioning of his eyes. Unfortunately, Labrador Retrievers can inherit or develop a number of different eye conditions, some of which may cause blindness if not treated right away, and most of which can be extremely painful! We will evaluate his eyes at every examination to look for any signs of concern.");
    dbFeed.addPetFeed("Dog", "Breed", 1,"Labrador", "Labrador: What a Unique Breed!", "Labradors are very sociable pets. Their chill, take-it-all-in-stride temperament and typically low aggression levels mean they are usually OK with being petted, cuddled and occasionally prodded. This easygoing attitude also means most Labradors will get along with other pets. However Labradors are large dogs , which means that very small children and frail older adults might be knocked down and potentially hurt due to Labradors' overly eager displays of affection.");

    dbFeed.addPetFeed("Dog", "Breed", 0,"Collie", "Your Collie’s Health", "Collie eye anomaly (CEA), also referred to as collie eye defect, is an inherited congenital condition. The chromosomes that determine the development of the eyes are mutated, so that the choroid (the collection of blood vessels that absorb scattered light and nourish the retina) is underdeveloped. The mutation can also result in other defects in the eye with more severe consequences, such as retinal detachment. When this mutation does occur, it is always in both eyes, although it might be more severe in one eye than the other.");
    dbFeed.addPetFeed("Dog", "Breed", 1,"Collie", "Collie: What a Unique Breed!", "The Collie originated as a shepherd’s dog in the Highlands of northern Scotland where it functioned as an all-purpose farm dog. After the Highland Clearances (1750 to 1860) breeding toward arbitrary breed-standards morphed the Collie into the dog we associate with Lassie today. So this dog has humble origins and it is known as one of the most placid, obedient, serene, and grateful members of the canine race.");
    dbFeed.addPetFeed("Dog", "Breed", 0,"Collie", "Your Collie’s Health", "Obesity can be a significant health problem in Collies. It is a serious disease that may cause or worsen joint problems, metabolic and digestive disorders, back pain and heart disease. Though it’s tempting to give your pal food when she looks at you with those soulful eyes, you can “love her to death” with leftover people food and doggie treats.");
    dbFeed.addPetFeed("Dog", "Breed", 1,"Collie", "Collie: What a Unique Breed!", "The well-bred Collie is sweet, friendly, and gentle. She is a family dog and enjoys being part of all household activities. Especially fond of kids, she enjoys playing with them and protectively watching over them. If those qualities weren't positive enough, the Collie tops them with her intelligence and loyalty.");

    
    dbFeed.addPetFeed("Dog","Age",0,"Young","Discipline your young  dog","Whenever possible, give treats, praise, and attention to your dog if it is behaving nicely. If you notice it lying next to something it used to chew, reward it. If instead of digging it plays with its toys, pet it. Your dog will quickly learn the difference between good and bad behavior.");
    dbFeed.addPetFeed("Dog","Age",1,"Young","Feed your young dog","Dogs require taurine, an essential amino acid, for heart and eye health. The food you choose should be balanced for the life stage of your dog or puppy. Properly balanced foods will contain taurine. You will need to provide fresh, clean water at all times, and wash and refill your dog's water bowls daily.");
    dbFeed.addPetFeed("Dog","Age",0,"Young","Don’t Treat Your Puppy Like an Adult Dog","Just as a human infant has vastly different needs than a teenager, a puppy will have care requirements distinct from those of a fully matured dog. In addition, you should consider a puppy’s various stages of development when caring for her.The socialization and training your dog receives during puppyhood will affect how well she will likely interact with people and other animals when she’s older.");
    dbFeed.addPetFeed("Dog","Age",1,"Young","Feed your young dog","Canines are natural carnivores and do not intentionally consume large quantities of carbohydrates. The domestic dog's liver has adapted to the lack of carbohydrates in the diet by using amino acids to produce glucose to fuel the brain and other tissues.Studies have shown that carbohydrate digestion in young puppies is much less effective than that of a mature canine with a developed gastrointestinal tract. Highly digestible carbohydrates can be found in commercial puppy food.");
    
    // general 

    dbFeed.addFeedToGeneral("0","Weight of a medium sized cat","If large domestic cats seem too big and small breeds seem tiny, a medium cat breed may be just right for you. These mid-sized cats typically weigh between 10 and 15 pounds, so they fit right into almost any home and environment, whether you live in a small apartment in the city or a big house in the suburbs.");
    dbFeed.addFeedToGeneral("0","Average life expectancy of an indoor dog","Average Life Expectancy (in captivity) of dogs depends on their size. For small dogs it is 13 years, whereas for medium dogs it is 11 years, and finally for large dogs it is 8 years.");
    dbFeed.addFeedToGeneral("0","Mongrels health","The theory of hybrid vigor suggests that as a group, pets of varied ancestry will be generally healthier than their purebred counterparts. In purebred pets, intentionally breeding pets of very similar appearance over several generations produces animals that carry many of the same alleles, some of which are detrimental.");
    dbFeed.addFeedToGeneral("0","Why dogs need a crate","Dogs need a den, or a small space just for them, to feel safe, cozy, and secure. When a crate is used appropriately, it can give dogs this feeling of a safe space and it can be a sanctuary for a dog. A crate can feel like a doghouse for the indoors. It can act as his bedroom, which is comforting and homey.");
    dbFeed.addFeedToGeneral("0","Why to adopt a pet","There are a lot of great reasons for adopting a rescue pet from a shelter. For one thing, they are usually house-trained, unlike a new puppy from the pet shop. They are also usually more loving and affectionate as they have gone through trauma in their past and are happy to have found someone who cares for them.");
    dbFeed.addFeedToGeneral("1","Average life expectancy of an indoor cat","Indoor cats live on average 10-15 years, while outdoor cats live on average 2-5 years This handout is intended to help you sort out the pros and cons associated with each lifestyle so you can rest assured your cat will have both an enriched life and protection from environmental hazards.");
    dbFeed.addFeedToGeneral("1","Weight of a medium sized dog","Medium dogs weigh between 20 and 60 pounds. Their height ranges between eight inches and 27 inches. Examples of medium-sized dogs are Beagle and Border Collie.");
    dbFeed.addFeedToGeneral("1","Take care of your pets","Attention, exercise, and play help pets (especially dogs) work off nervous energy, tone muscles, and maintain a healthy weight. The quality time you spend with your pet also helps support your animal's emotional health—whether you're walking in the woods or just cuddling on the couch.");
    dbFeed.addFeedToGeneral("1","Why cats need a crate","Cats need a den, or a small space just for them, to feel safe, cozy, and secure. When a crate is used appropriately, it can give cats this feeling of a safe space and it can be a sanctuary for a cat. A crate can feel like a cathouse for the indoors. It can act as his bedroom, which is comforting and homey.");
    dbFeed.addFeedToGeneral("1","Pet therapy","Pet therapy has been shown to improve patient satisfaction, energy levels, self-esteem, and mood, as well as decrease depression. Additional benefits include increased motor skills and movement, improved social skills and verbal communication, decreased boredom, and a more positive outlook.");
    
    dbFeed.addPetFeed("Dog","Age",0,"Young","Discipline your young  dog","Whenever possible, give treats, praise, and attention to your dog if it is behaving nicely. If you notice it lying next to something it used to chew, reward it. If instead of digging it plays with its toys, pet it. Your dog will quickly learn the difference between good and bad behavior.");
    dbFeed.addPetFeed("Dog","Age",1,"Young","Feed your young dog","Dogs require taurine, an essential amino acid, for heart and eye health. The food you choose should be balanced for the life stage of your dog or puppy. Properly balanced foods will contain taurine. You will need to provide fresh, clean water at all times, and wash and refill your dog's water bowls daily.");
    dbFeed.addPetFeed("Dog","Age",0,"Young","Don’t Treat Your Puppy Like an Adult Dog","Just as a human infant has vastly different needs than a teenager, a puppy will have care requirements distinct from those of a fully matured dog. In addition, you should consider a puppy’s various stages of development when caring for her.The socialization and training your dog receives during puppyhood will affect how well she will likely interact with people and other animals when she’s older.");
    dbFeed.addPetFeed("Dog","Age",1,"Young","Feed your young dog","Canines are natural carnivores and do not intentionally consume large quantities of carbohydrates. The domestic dog's liver has adapted to the lack of carbohydrates in the diet by using amino acids to produce glucose to fuel the brain and other tissues.Studies have shown that carbohydrate digestion in young puppies is much less effective than that of a mature canine with a developed gastrointestinal tract. Highly digestible carbohydrates can be found in commercial puppy food.");
    
    
    dbFeed.addPetFeed("Dog","Age",0,"Old","Provide special accomodation to old dogs","Older dogs often develop arthritis or other bone and joint problems that affect their mobility. Furthermore, a blind dog will also have trouble jumping on the bed or sofa at night.In these cases, your dog can benefit from soft bedding and an easily accessible bed that won't require jumping or climbing.");
    dbFeed.addPetFeed("Dog","Age",1,"Old","Feed your old dog","A balanced diet plays a big role in maintaining your dog's health even when they age. Older dogs are at higher risk of developing obesity since they no longer have the same levels of energy as before. So it is important to find the best dog food that is specially designed for senior dogs in order to prevent weight gain.These are often low in fat and have fewer calories that will complement the nutritional need of your dog.");
    dbFeed.addPetFeed("Dog","Age",0,"Old","Regular grooming","As your dog ages, so do their coat and skin, a once luxurious and shiny coat can become dull looking and brittle. Seniors can also suffer from dry, flaky, and irritated skin that can become even worse if not cared for properly.That means that you will have to brush your dog regularly, especially to avoid the development of mats and tangles. We also recommend that you use only natural shampoos that will nourish and heal irritated skin and coat.");
    dbFeed.addPetFeed("Dog","Age",1,"Old","Regular vet checkups","Regular vet care is one of the most important things when it comes to caring for older dogs. As your dog ages, their immune system becomes weaker, which makes them more prone to all sorts of ailments.That's why most vets recommend taking an older dog for regular checkups once every six months.This will give your vet a chance to figure if anything is wrong at the beginning and provide the best possible treatment for your dog.");

    dbFeed.addPetFeed("Cat","Age",0,"Old","Provide special accomodation to old cats","Older cats often develop arthritis or other bone and joint problems that affect their mobility. Furthermore, a blind cat will also have trouble jumping on the bed or sofa at night.In these cases, your cat can benefit from soft bedding and an easily accessible bed that won't require jumping or climbing.");
    dbFeed.addPetFeed("Cat","Age",1,"Old","Feed your old cat","A balanced diet plays a big role in maintaining your cat's health even when they age. Older cats are at higher risk of developing obesity since they no longer have the same levels of energy as before. So it is important to find the best cat food that is specially designed for senior cats in order to prevent weight gain.These are often low in fat and have fewer calories that will complement the nutritional need of your cat.");
    dbFeed.addPetFeed("Cat","Age",0,"Old","Regular grooming","As your cat ages, so do their coat and skin, a once luxurious and shiny coat can become dull looking and brittle. Seniors can also suffer from dry, flaky, and irritated skin that can become even worse if not cared for properly.That means that you will have to brush your cat regularly, especially to avoid the development of mats and tangles. We also recommend that you use only natural shampoos that will nourish and heal irritated skin and coat.");
    dbFeed.addPetFeed("Cat","Age",1,"Old","Regular vet checkups","Regular vet care is one of the most important things when it comes to caring for older cats. As your cat ages, their immune system becomes weaker, which makes them more prone to all sorts of ailments.That's why most vets recommend taking an older cat for regular checkups once every six months.This will give your vet a chance to figure if anything is wrong at the beginning and provide the best possible treatment for your cat.");
    
    dbFeed.addPetFeed("Dog","Age",0,"Medium","Regular exercise","As a dog ages, they have lower energy levels, so even though your pup was able to run for half an hour before, they might not be able to do it once they get older. Regular exercise will help your dog maintain their ideal weight and will also have a beneficial impact on their overall health. Be patient, start slowly and build your dog's stamina with regular walks and light jogs if they are able to run. ");
    dbFeed.addPetFeed("Dog","Age",1,"Medium","Maintain oral health","Most old dogs don't get the proper dental care during their adult life, so it is not uncommon to see older dogs with a few missing teeth. Dental care is an important part of grooming and should be performed regularly from a young age. To keep your dog's teeth healthy, you need to wash them every day, and if your dog isn't a fan, start giving them dental treats. Also, you should take your dog to the vet once a year in order to have their teeth professionally cleaned.");
    dbFeed.addPetFeed("Dog","Age",0,"Medium","Vaccination and parasite protection","Your dog's age doesn't matter when it comes to flea, tick, and worm protection. So you should continue administering proper treatments just like before. But when it comes to vaccines, older dogs don't require them at the same intervals. Usually once every three years is enough, but you should consult your vet since they will know what is best for your dog's individual needs.");
    dbFeed.addPetFeed("Dog","Age",1,"Medium","Train your dog","While most people associate training with puppies, the reality is that dogs can learn at any age. Adult dogs are often easier to train than young puppies because they have more self-control. It's also important to keep training your dog as it matures.");
    
    dbFeed.addPetFeed("Cat","Age",0,"Medium","Regular exercise","As a cat ages, they have lower energy levels, so even though your pup was able to run for half an hour before, they might not be able to do it once they get older. Regular exercise will help your cat maintain their ideal weight and will also have a beneficial impact on their overall health. Be patient, start slowly and build your cat's stamina with regular walks and light jogs if they are able to run. ");
    dbFeed.addPetFeed("Cat","Age",1,"Medium","Maintain oral health","Most old cats don't get the proper dental care during their adult life, so it is not uncommon to see older cats with a few missing teeth. Dental care is an important part of grooming and should be performed regularly from a young age. To keep your cat's teeth healthy, you need to wash them every day, and if your cat isn't a fan, start giving them dental treats. Also, you should take your cat to the vet once a year in order to have their teeth professionally cleaned.");
    dbFeed.addPetFeed("Cat","Age",0,"Medium","Vaccination and parasite protection","Your cat's age doesn't matter when it comes to flea, tick, and worm protection. So you should continue administering proper treatments just like before. But when it comes to vaccines, older cats don't require them at the same intervals. Usually once every three years is enough, but you should consult your vet since they will know what is best for your cat's individual needs.");
    dbFeed.addPetFeed("Cat","Age",1,"Medium","Train your cat","While most people associate training with kittens, the reality is that cats can learn at any age. Adult cats are often easier to train than young puppies because they have more self-control. It's also important to keep training your cat as it matures.");
    
    dbFeed.addPetFeed("Dog","Size",0,"Small","How much should a small-sized dog eat a day?","That's a question best answered by a professional, though recommendations range between 26 to 37 calories a day per pound, to keep dogs at a normal, healthy weight.");
    dbFeed.addPetFeed("Dog","Size",0,"Small","Train a small dog"," Small dogs can be more difficult to train than large dogs. They tend to be more territorial indoors than larger dogs who often view the great outdoors as their main turf. However, some small breeds can be litter-box trained, so score one for their size! ");
    dbFeed.addPetFeed("Dog","Size",1,"Small","Smaller size, longer life","Little dogs generally live longer than larger breeds. However, small breeds do have health-specific issues like leg and joint issues, including hip dysplasia when the bone doesn't fit properly in the hip socket, or a slipped kneecap, making them prone to arthritis.");
    dbFeed.addPetFeed("Dog","Size",1,"Small","Exercise, socialize","Proper training and socializing with other dogs is necessary to help channel all of your little guy’s high-octane energy. With a healthy amount of exercise and socialization skills under his collar, you can avoid the yappy and skittish qualities too often associated with small breeds.");
    
    dbFeed.addPetFeed("Cat","Size",0,"Small","Exercise, socialize","Proper training and socializing with other cats is necessary to help channel all of your little guy’s high-octane energy. With a healthy amount of exercise and socialization skills under his collar, you can avoid the yappy and skittish qualities too often associated with small breeds.");
    
    dbFeed.addPetFeed("Dog","Size",0,"Large","Feed your large dog"," Because smaller dogs have more energy than larger breeds, they need extra calories to meet those needs. Large dogs may wolf down more food but they have different nutritional requirements, including ingredients that support joint health and overall movement.");
    dbFeed.addPetFeed("Dog","Size",0,"Large","Train a large dog","Large dogs tend to bond with and get attached to their owners quickly and can easily be trained. Some breeds are easier to train than others, but all-in-all larger dogs are easier to train than smaller ones");
    dbFeed.addPetFeed("Dog","Size",1,"Large","More emotionally stable","Yep, that’s right, larger dogs are more emotionally stable. And often dogs become your comforter when you need them. Not to mention, they make the best cuddle buddies and love to sleep in the bed with you.");
    dbFeed.addPetFeed("Dog","Size",1,"Large","Shorter lifespan","At its simplest, larger dogs die younger because they age more quickly. They age more quickly because they grow faster. This can lead to earlier incidence of tumors and other abnormal tissue developments, including cancer.");
    
    dbFeed.addPetFeed("Cat","Size",0,"Large","Feed your large cat"," Because smaller cats have more energy than larger breeds, they need extra calories to meet those needs. Large cats may wolf down more food but they have different nutritional requirements, including ingredients that support joint health and overall movement.");
    dbFeed.addPetFeed("Cat","Size",0,"Large","Train a large cat","Large cats tend to bond with and get attached to their owners quickly and can easily be trained. Some breeds are easier to train than others, but all-in-all larger cats are easier to train than smaller ones");
    dbFeed.addPetFeed("Cat","Size",1,"Large","More emotionally stable","Yep, that’s right, larger cats are more emotionally stable. And often cats become your comforter when you need them. Not to mention, they make the best cuddle buddies and love to sleep in the bed with you.");
    dbFeed.addPetFeed("Cat","Size",1,"Large","Shorter lifespan","At its simplest, larger cats die younger because they age more quickly. They age more quickly because they grow faster. This can lead to earlier incidence of tumors and other abnormal tissue developments, including cancer.");
    
    dbFeed.addPetFeed("Dog","Size",1,"Medium","Longer life","The average life span of a medium-sized dog is 12-15 years. They age slower than large dog breeds and have nearly the same life expectancy as small dog breeds. Some individuals may live longer depending on their genetics, as well as the nutrition and preventative care they receive during their lifetime.");
    dbFeed.addPetFeed("Dog","Size",1,"Medium","Train a medium dog","Medium dogs tend to bond with and get attached to their owners quickly and can easily be trained. Some breeds are easier to train than others, but all-in-all medium dogs are easier to train than smaller ones, even if a little bit less easier than average large-size breeds");
    dbFeed.addPetFeed("Dog","Size",0,"Medium","More emotionally stable","Yep, that’s right, larger cats are more emotionally stable. And often cats become your comforter when you need them. Not to mention, they make the best cuddle buddies and love to sleep in the bed with you.");
    dbFeed.addPetFeed("Dog","Size",0,"Medium","Feed your middle-size dog","Some research suggests that certain breeds are more susceptible to health problems related to food allergies.Many of these at-risk breeds are mid-weight dogs.As a dog owner, you should look out for the signs of a food allergy: itching, swollen eyelids, flatulence, and digestive problems. The most common allergens are beef, dairy, and wheat. A vet can help you determine which food ingredient is the culprit.");

    dbFeed.addPetFeed("Cat","Size",1,"Medium","Longer life","The average life span of a medium-sized cat is 14-17 years. They age slower than large cat breeds and have nearly the same life expectancy as small cat breeds. Some individuals may live longer depending on their genetics, as well as the nutrition and preventative care they receive during their lifetime.");
    dbFeed.addPetFeed("Cat","Size",1,"Medium","Train a medium cat","Medium cats tend to bond with and get attached to their owners quickly and can easily be trained. Some breeds are easier to train than others, but all-in-all medium cats are easier to train than smaller ones, even if a little bit less easier than average large-size breeds");
    dbFeed.addPetFeed("Cat","Size",0,"Medium","More emotionally stable","Yep, that’s right, medium cats are more emotionally stable. And often cats become your comforter when you need them. Not to mention, they make the best cuddle buddies and love to sleep in the bed with you.");
    dbFeed.addPetFeed("Cat","Size",0,"Medium","Feed your middle-size cat","Some research suggests that certain breeds are more susceptible to health problems related to food allergies.Many of these at-risk breeds are mid-weight cats.As a cat owner, you should look out for the signs of a food allergy: itching, swollen eyelids, flatulence, and digestive problems. The most common allergens are beef, dairy, and wheat. A vet can help you determine which food ingredient is the culprit.");
    */
    
});

afterAll(() => { //run with --detectOpenHandles
    
});



test("addds", () => {

   let animals = [new UserAnimal("name", 2, "Bombay", "Small", "black", "photo","Cat"),
                  new UserAnimal("name", 2, "None", "Small", "black", "photo","Cat")];
    //filtered = dbFeed.filterAnimals(animals);              
    expect(dbFeed.getFeeds([],"gbfBtH1XbDMYice2pM0zV7caEjn2","03/06/2021",0)).resolves.toHaveLength(4);
    //expect(dbFeed.getRandomGeneralFeeds("gbfBtH1XbDMYice2pM0zV7caEjn2","Cat",0)).resolves.toBeInstanceOf(Feed);
});



