const constants = {
  TYPES_PLACES: ["Veterinary", "Park", "Kennel", "Other"],

  SIZES_PETS: ["Small", "Medium", "Big"],

  TYPES_PETS: ["Dog", "Cat"],

  FEED_TYPE: {
    general: "General",
    breed: "Breed",
    age: "Age",
    size: "size",
  },

  COLORS_PETS: [
    "Apricot",
    "Black",
    "Blue",
    "Brindle",
    "Brown",
    "Cream",
    "Dapple",
    "Fawn",
    "Grizzle",
    "Merle",
    "Orange",
    "Particolor",
    "Red",
    "Roan",
    "White",
    "Yellow",
  ],

  BREEDS_CAT: [
    "None",
    "Abyssinian",
    "Aegean",
    "American",
    "Aphrodite Giant",
    "Arabian Mau",
    "Asian",
    "Australian Mist",
    "Balinese",
    "Bengal",
    "Birman",
    "Bombay",
    "Brazilian",
    "British",
    "Burmese",
    "Burmilla",
    "California-Spangled",
    "Chantilly-Tiffany",
    "Chartreux",
    "Chausie",
    "Colorpoint",
    "Cornish Rex",
    "Cymric",
    "Cyprus",
    "Devon Rex",
    "Donskoy",
    "Dragon Li",
    "Dwelf",
    "Egyptian Mau",
    "European",
    "Exotic",
    "Foldex",
    "German Rex",
    "Havana Brown",
    "Highlander",
    "Himalayan",
    "Japanese Bobtail",
    "Javanese",
    "Kanaani",
    "Khao Manee",
    "Kinkalow",
    "Korat",
    "Korean Bobtail",
    "Korn Ja",
    "Kurilian Bobtail",
    "Lambkin",
    "LaPerm",
    "Lykoi",
    "Maine Coon",
    "Manx",
    "Mekong",
    "Minskin",
    "Napoleon",
    "Munchkin",
    "Nebelung",
    "Norwegian Forest",
    "Ocicat",
    "Ojos Azules",
    "Oriental",
    "Persian",
    "Peterbald",
    "Pixie-bob",
    "Ragamuffin",
    "Ragdoll",
    "Raas",
    "Russian",
    "Sam Sawet",
    "Savannah",
    "Scottish Fold",
    "Selkirk Rex",
    "Serengeti",
    "Serrade Petit",
    "Siamese",
    "Siberian",
    "Singapura",
    "Snowshoe",
    "Sokoke",
    "Somali",
    "Sphynx",
    "Suphalak",
    "Thai",
    "Tonkinese",
    "Toyger",
    "Turkish",
    "Ukrainian Levkoy",
    "York Chocolate",
  ],

  BREEDS_DOG: [
    "None",
    "Affenpinscher",
    "African",
    "Airedale",
    "Akita",
    "Appenzeller",
    "Australian",
    "Basenji",
    "Beagle",
    "Bluetick",
    "Borzoi",
    "Bouvier",
    "Boxer",
    "Brabancon",
    "Briard",
    "Buhund",
    "Bulldog",
    "Bullterrier",
    "Cairn",
    "Cattledog",
    "Chihuahua",
    "Chow",
    "Clumber",
    "Cockapoo",
    "Collie",
    "Coonhound",
    "Corgi",
    "Cotondetulear",
    "Dachshund",
    "Dalmatian",
    "Dane",
    "Deerhound",
    "Dhole",
    "Dingo",
    "Doberman",
    "Elkhound",
    "Entlebucher",
    "Eskimo",
    "Finnish",
    "Frise",
    "Germanshepherd",
    "Greyhound",
    "Groenendael",
    "Havanese",
    "Hound",
    "Husky",
    "Keeshond",
    "Kelpie",
    "Komondor",
    "Kuvasz",
    "Labradoodle",
    "Labrador",
    "Leonberg",
    "Lhasa",
    "Malamute",
    "Malinois",
    "Maltese",
    "Mastiff",
    "Mexicanhairless",
    "Mix",
    "Mountain",
    "Newfoundland",
    "Otterhound",
    "Ovcharka",
    "Papillon",
    "Pekinese",
    "Pembroke",
    "Pinscher",
    "Pitbull",
    "Pointer",
    "Pomeranian",
    "Poodle",
    "Pug",
    "Puggle",
    "Pyrenees",
    "Redbone",
    "Retriever",
    "Ridgeback",
    "Rottweiler",
    "Saluki",
    "Samoyed",
    "Schipperke",
    "Schnauzer",
    "Setter",
    "Sheepdog",
    "Shiba",
    "Shihtzu",
    "Spaniel",
    "Springer",
    "Stbernard",
    "Terrier",
    "Vizsla",
    "Waterdog",
    "Weimaraner",
    "Whippet",
    "Wolfhound",
  ],

  DISEASES_CAT: [
    "Acne",
    "Aspergillosis",
    "Cancer",
    "Coccidia",
    "Coronavirus",
    "Cystitis",
    "Deafness",
    "Diabetes",
    "Distemper",
    "Fleas",
    "Flu",
    "Hyperthyroidism",
    "Immunodeficiency",
    "Leptospirosis",
    "Leukemia",
    "Lymphoma",
    "Lymphocytopenia",
    "Mastocytoma",
    "Rabies",
    "Salmonellosis",
    "Tetanus",
    "Thelaziasis",
    "Toxocariasis",
  ],

  DISEASES_DOG: [
    "Acromegaly",
    "Blastomycosis",
    "Cancer",
    "Cataracts",
    "Clostridium",
    "Coronavirus",
    "Cystitis",
    "Deafness",
    "Diabetes",
    "Distemper",
    "Epilepsy",
    "Fibrosarcoma",
    "Fleas",
    "Flu",
    "Hyperthyroidism",
    "Leptospirosis",
    "Leukemia",
    "Lymphoma",
    "Melanomas",
    "Osteosarcoma",
    "Pancreatitis",
    "Parvovirus",
    "Pyometra",
    "Rabies",
    "Tetanus",
  ],
};

export default constants;
